---
- name: Create local backup dir and scripts dir
  file:
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ local_backup_dir }}"
    - "{{ backup_scripts_path }}"

- name: Template backup scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    mode: 0755
    backup: true
  with_items:
    - {
        src: ansible_postgres_backup_daily.sh.j2,
        dest: "{{ backup_scripts_path }}/ansible_postgres_backup_daily.sh",
      }
    - {
        src: ansible_postgres_backup_weekly.sh.j2,
        dest: "{{ backup_scripts_path }}/ansible_postgres_backup_weekly.sh",
      }

- name: Add cron jobs
  cron:
    name: "{{ item.name }}"
    user: postgres
    minute: "{{ item.minute }}"
    hour: "1"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
  with_items:
    - {
        name: "PostgreSQL Daily Backup",
        minute: "0",
        weekday: "*",
        job: "{{ backup_scripts_path }}/ansible_postgres_backup_daily.sh",
      }
    - {
        name: "PostgreSQL Weekly Backup",
        minute: "5",
        weekday: "6",
        job: "{{ backup_scripts_path }}/ansible_postgres_backup_weekly.sh",
      }
